server:
  port: 9999
  context-path: /shiro_web
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhao?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123123
  redis:
    host: 192.168.255.129
    port: 10004
  http:
    multipart:
      max-file-size: 30Mb
      maxRequestSize: 30Mb

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity